#! /bin/bash

# Criado por Alvarinho Luis
# Objetivo: Acessar privilégios de root no Termux
# Data: 12 de Janeiro de 2023
# Nota: ESTA FERRAMENTA É APENAS PARA USO LEGAL E JUSTO

clear
echo -e "\e[1;31m"

xdg-open https://m.youtube.com/@Termuxhacker131

echo "Pressione ENTER para continuar..."
read


echo -e "\e[0m"echo -e "\e[0m"
mv /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc_old
cp -v bash.bashrc /data/data/com.termux/files/usr/etc/bash.bashrc
clear

apt-get update && apt-get upgrade -y
pkg  install fish  ncurses-utils proot proot-distro tsu fakeroot parted -y

cliiear

echo -e "\e[1;31m"
echo " ██▀███      ▒█████      ▒█████     ▄▄▄█████▓"
echo "▓██ ▒ ██▒   ▒██▒  ██▒   ▒██▒  ██▒   ▓  ██▒ ▓▒"
echo "▓██ ░▄█ ▒   ▒██░  ██▒   ▒██░  ██▒   ▒ ▓██░ ▒░"
echo "▒██▀▀█▄     ▒██   ██░   ▒██   ██░   ░ ▓██▓ ░ "
echo "░██▓ ▒██▒   ░ ████▓▒░   ░ ████▓▒░     ▒██▒ ░ "
echo "░ ▒▓ ░▒▓░   ░ ▒░▒░▒░    ░ ▒░▒░▒░      ▒ ░░   "
echo "  ░▒ ░ ▒░     ░ ▒ ▒░      ░ ▒ ▒░        ░    "
echo "  ░░   ░    ░ ░ ░ ▒     ░ ░ ░ ▒       ░      "
echo "   ░            ░ ░         ░ ░              "
echo -e "\e[1;33m                                 ROOT TERMUX"

echo -e "\e[1;32m"
clear

echo "            YouTube: Termux Hacker"
echo "            YouTube: Alvarinho Luis"
echo -e "\e[1;36m\n"
echo "[*] Automação iniciada"
sleep 1
echo "[*] Sincronizando"
sleep 0.5
echo "[*] Coletando pacotes"
echo "[*] Preparando arquivos"
sleep 0.5
echo "[*] Fornecendo acesso ROOT"
echo "[*] Feito"

sleep 1.5

clear
echo -e "\e[1;34mESCREVA \e[1;32mroot\e[1;34m para accessar o falso root privigeliado"
echo -e "ESCREVA \e[1;32falso\e[1;34m PARA ACESSAR PRIVILÉGIOS ROOT REAIS"
read

clear
echo -e "\e[1;33m"

echo "            YouTube: Termux Hacker"
echo "            YouTube: Alvary valley"
echo "            YouTube: Alvarinho Luis"
echo -e "\e[0;34m\n"
